### ISSUE TITLE
bus.sendError() disconnects from the bus

### ISSUE THREAD

**Issue by nschoe** [sidorares/node-dbus#122]
I'm trying to use the `sendError()` function to return some errors to a method call, but when I do that, the services disconnects form the bus without sending the answer. At the other end, the method caller returns with "recipient disconnecting without replying".

This is much infortunate because it seems I can't return some errors to the caller. I can't seem to track the moment it happens.

`sendError()` calls `connection.message()`, which just marshals the message. I have put some `console.log()` in the `stream.on('end')` event, which does get called, but I cannot find where or what causes the stream to end.

Can someone point me to the right direction?

Thanks in advance.

**Comment by sidorares** [comment]
would you be able to start wireshark and capture data just before disconnect?

**Comment by nschoe** [comment]
Hum maybe I can try. This is a tricky setup that I have, since I have the scripts run in a Docker container. What filter do I sue on wireshark to get those packets? On what interface should I listen?

**Comment by nschoe** [comment]
Hum I just tried on my host (no container), I have started wireshark and sent `gdbus introspect` calls, but I could not find it on wireshark (on `any` interface).
Maybe I'm doing something wrong.

Do you have any idea why the script disconnects from DBus?

**Comment by sidorares** [comment]
if there is no crash/errors on script side it's likely dbus daemon disconnected it. Maybe bug in serialisation, maybe something else

**Comment by nschoe** [comment]
It seems to happen on `stream.write()` [here](https://github.com/sidorares/node-dbus/blob/master/index.js#L132).

I'll be investigating, in the meantime, if you have some ideas...

Thanks for answering so quickly ^^

**Comment by sidorares** [comment]
could you console.log(msg) and `message.marshall(msg).toString('hex')` just before that line?

**Comment by nschoe** [comment]
Yes, sure, here it is:

```console.log(msg):

{ type: 3,
  replySerial: 11,
  destination: ':1.206',
  errorName: 'Error',
  signature: 's',
  body: [ 'Error thrown from Avatar' ],
  serial: 1 }
```

And
```message.marshall(msg).toString('hex'): 

'6c0300011d000000010000002f00000004017300050000004572726f72000000050175000b00000006017300060000003a312e32303600000801670001730000180000004572726f72207468726f776e2066726f6d2041766174617200'
```

Does that help?

**Comment by sidorares** [comment]
yes, thanks. I'll try to check

**Comment by nschoe** [comment]
Okay good. For information, I used `node debug` to try and find the error, I stepped in as deep as I could and I eventually reach the error in the core or the `net.js` library, at the moment it writes to the buffer.
But I don't get a chance to see why, even with `step in` the error just "happens", it seems atomic, I cannot decompose it further :/

**Comment by sidorares** [comment]
I can reproduce this, investigating

**Comment by nschoe** [comment]
I have tried another thing,, here it is.
First, I fixed a typo bug [here](https://github.com/sidorares/node-dbus/blob/master/lib/bus.js#L93), in `sendReply()`, the last line, the one actually sending the message is `this.connection.message(msg)` and I replaced it with `this.connection.message(reply)`.

I confirmed it worked ok: the service does send an answer when I call `self.sendReply()`. Then I temporarily edited the code of `sendReply()` to replace `type: constants.messageType.methodReturn` with `type: constants.messageType.error` and then it does exactly as before: disconnect from bus.

So apparently, this is inherently linked to the fact that the `type` field is set to `error`. But I cannot find a clue (yet) as to why.

**P.S.:** shall I send a merge request to fix the `sendReply()` command?

**Comment by sidorares** [comment]
@nschoe try to set errorName to something which looks like valid interface. I tried sending error with "foo" as errorName and the server was disconnected, and when I used 'com.example.MusicPlayer.Error.OutOfMemory' the error was delivered to caller.

https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names-error

> ### Error names
>
> Error names have the same restrictions as interface names.
> Error names have the same naming conventions as interface names, and often contain .Error.; for instance, the owner of example.com might define the errors com.example.MusicPlayer.Error.FileNotFound and com.example.MusicPlayer.Error.OutOfMemory. The errors defined by D-Bus itself, such as org.freedesktop.DBus.Error.Failed, follow a similar pattern.

**Comment by sidorares** [comment]
> shall I send a merge request to fix the sendReply() command?

yes please! ( though this might actually been fixed as part of #118 , unfortunately still don't have time to finish that )

**Comment by sidorares** [comment]
might be a good idea to add the check for `errorName` to the client so it'll fail early with clear message how to fix. Need to investigate what exactly is name requirement and why "foo" is not valid name

**Comment by nschoe** [comment]
Ah! Thanks, you were right for the error name, it must contain a dot (.). Setting the error name to `foo.bar` works.
Great! Might add a little comment as a reminder, though.

Thanks for your help!

I'm submitting the PR for the typo ;-)

**Comment by nschoe** [comment]
Added a comment to remind people of this in `sendError()`.
